spring.datasource.url=jdbc:postgresql://localhost:5432/Magic8BallAnswers
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always


## datasource connection properties
#spring.datasource.url=jdbc:postgresql://localhost:5432/magic8Ball
#
#spring.datasource.username=postgres
#spring.datasource.password=finalcapstone
#
#spring.sql.init.mode=always