# datasource connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/magic8Ball

spring.datasource.username=postgres
spring.datasource.password=finalcapstone 

spring.sql.init.mode=always